<a href="https://colab.research.google.com/github/bajichaghan-glitch/KBUstart/blob/main/20261042_%EA%B9%80%EC%9E%AC%EC%9D%BC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
DB_URL = "https://github.com/lerocha/chinook-database/raw/master/ChinookDatabase/DataSources/Chinook_Sqlite.sqlite"
DB_PATH = "chinook.db"

In [25]:
os.path.exists(DB_PATH)
import requests

In [26]:
import os
DB_PATH = "chinook.db"
os.path.exists(DB_PATH)

True

In [27]:
import sqlite3
import pandas as pd

db_path = '/content/chinook.db'

with sqlite3.connect(db_path) as conn:
    # 1. sqlite_master 테이블에서 모든 테이블 이름 조회
    cursor = conn.cursor()
    cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
    tables = [table[0] for table in cursor.fetchall()]

    print(f"📊 발견된 테이블 목록 (총 {len(tables)}개):")
    print(tables)
    print("\n" + "="*50 + "\n")

    # 2. 각 테이블에서 데이터를 상위 3개씩 출력
    for table_name in tables:
        print(f"🔹 [Table: {table_name}]")
        query = f"SELECT * FROM `{table_name}` LIMIT 3;"
        df = pd.read_sql_query(query, conn)
        display(df)
        print("-" * 50)

📊 발견된 테이블 목록 (총 11개):
['Album', 'Artist', 'Customer', 'Employee', 'Genre', 'Invoice', 'InvoiceLine', 'MediaType', 'Playlist', 'PlaylistTrack', 'Track']

==================================================

🔹 [Table: Album]

   AlbumId                                  Title  ArtistId
0        1  For Those About To Rock We Salute You         1
1        2                      Balls to the Wall         2
2        3                      Restless and Wild         2

--------------------------------------------------
🔹 [Table: Artist]

   ArtistId       Name
0         1      AC/DC
1         2     Accept
2         3  Aerosmith

--------------------------------------------------
🔹 [Table: Customer]

,CustomerId,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
0,1,Luís,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,+55 (12) 3923-5566,luisg@embraer.com.br,3
1,2,Leonie,Köhler,None,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,+49 0711 2842222,None,leonekohler@surfeu.de,5
2,3,François,Tremblay,None,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,+1 (514) 721-4711,None,ftremblay@gmail.com,3

--------------------------------------------------
🔹 [Table: Employee]

,EmployeeId,LastName,FirstName,Title,ReportsTo,BirthDate,HireDate,Address,City,State,Country,PostalCode,Phone,Fax,Email
0,1,Adams,Andrew,General Manager,NaN,1962-02-18 00:00:00,2002-08-14 00:00:00,11120 Jasper Ave NW,Edmonton,AB,Canada,T5K 2N1,+1 (780) 428-9482,+1 (780) 428-3457,andrew@chinookcorp.com
1,2,Edwards,Nancy,Sales Manager,1.0,1958-12-08 00:00:00,2002-05-01 00:00:00,825 8 Ave SW,Calgary,AB,Canada,T2P 2T3,+1 (403) 262-3443,+1 (403) 262-3322,nancy@chinookcorp.com
2,3,Peacock,Jane,Sales Support Agent,2.0,1973-08-29 00:00:00,2002-04-01 00:00:00,1111 6 Ave SW,Calgary,AB,Canada,T2P 5M5,+1 (403) 262-3443,+1 (403) 262-6712,jane@chinookcorp.com

--------------------------------------------------
🔹 [Table: Genre]

   GenreId   Name
0        1   Rock
1        2   Jazz
2        3  Metal

--------------------------------------------------
🔹 [Table: Invoice]

,InvoiceId,CustomerId,InvoiceDate,BillingAddress,BillingCity,BillingState,BillingCountry,BillingPostalCode,Total
0,1,2,2021-01-01 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,1.98
1,2,4,2021-01-02 00:00:00,Ullevålsveien 14,Oslo,None,Norway,0171,3.96
2,3,8,2021-01-03 00:00:00,Grétrystraat 63,Brussels,None,Belgium,1000,5.94

--------------------------------------------------
🔹 [Table: InvoiceLine]

   InvoiceLineId  InvoiceId  TrackId  UnitPrice  Quantity
0              1          1        2       0.99         1
1              2          1        4       0.99         1
2              3          2        6       0.99         1

--------------------------------------------------
🔹 [Table: MediaType]

   MediaTypeId                         Name
0            1              MPEG audio file
1            2     Protected AAC audio file
2            3  Protected MPEG-4 video file

--------------------------------------------------
🔹 [Table: Playlist]

   PlaylistId      Name
0           1     Music
1           2    Movies
2           3  TV Shows

--------------------------------------------------
🔹 [Table: PlaylistTrack]

   PlaylistId  TrackId
0           1     3402
1           1     3389
2           1     3390

--------------------------------------------------
🔹 [Table: Track]

,TrackId,Name,AlbumId,MediaTypeId,GenreId,Composer,Milliseconds,Bytes,UnitPrice
0,1,For Those About To Rock (We Salute You),1,1,1,"Angus Young, Malcolm Young, Brian Johnson",343719,11170334,0.99
1,2,Balls to the Wall,2,2,1,"U. Dirkschneider, W. Hoffmann, H. Frank, P. Ba...",342562,5510424,0.99
2,3,Fast As a Shark,3,2,1,"F. Baltes, S. Kaufman, U. Dirkscneider & W. Ho...",230619,3990994,0.99

--------------------------------------------------

In [28]:
import os
import requests

DB_URL = "https://github.com/lerocha/chinook-database/raw/master/ChinookDatabase/DataSources/Chinook_Sqlite.sqlite"
DB_PATH = "chinook.db"

def download_chinook_db():
    if not os.path.exists(DB_PATH):
        print("📥 Downloading Chinook database...")
        response = requests.get(DB_URL)
        with open(DB_PATH, "wb") as f:
            f.write(response.content)
        print("✅ Download complete.")
    else:
        print("✅ Chinook DB already exists.")

download_chinook_db()

✅ Chinook DB already exists.

In [29]:
import sqlite3

# Define the database path
DB_PATH = "chinook.db"

# Connect to the SQLite database
conn = sqlite3.connect(DB_PATH)

# Get a list of all tables in the database
cursor = conn.cursor()
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
tables = cursor.fetchall()

print("Available tables in the database:", [table[0] for table in tables])
conn.close()

Available tables in the database: ['Album', 'Artist', 'Customer', 'Employee', 'Genre', 'Invoice', 'InvoiceLine', 'MediaType', 'Playlist', 'PlaylistTrack', 'Track']

In [30]:
import os
import requests
import sqlite3

DB_URL = "https://github.com/lerocha/chinook-database/raw/master/ChinookDatabase/DataSources/Chinook_Sqlite.sqlite"
DB_PATH = "chinook.db"

# 1. 기존의 잘못된(빈) 파일이 있다면 삭제합니다.
if os.path.exists(DB_PATH):
    os.remove(DB_PATH)
    print("🧹 Existing empty database removed.")

# 2. 데이터베이스를 새로 다운로드합니다.
print("📥 Downloading Chinook database...")
response = requests.get(DB_URL)
with open(DB_PATH, "wb") as f:
    f.write(response.content)
print("✅ Download complete.")

# 3. 다시 테이블 목록을 조회하여 확인합니다.
conn = sqlite3.connect(DB_PATH)
cursor = conn.cursor()
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
tables = cursor.fetchall()
print("📊 Available tables in the database:", [table[0] for table in tables])
conn.close()

🧹 Existing empty database removed.
📥 Downloading Chinook database...
✅ Download complete.
📊 Available tables in the database: ['Album', 'Artist', 'Customer', 'Employee', 'Genre', 'Invoice', 'InvoiceLine', 'MediaType', 'Playlist', 'PlaylistTrack', 'Track']

In [31]:
# @title 모든 테이블을 사전형으로 읽기
# Initialize a dictionary to store all DataFrames
dfs = {}

# Connect to the SQLite database using a 'with' statement
with sqlite3.connect(DB_PATH) as conn:
    cursor = conn.cursor()
    cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
    tables = cursor.fetchall()

    # Iterate through each table and load it into a DataFrame
    for table_name in [table[0] for table in tables]:
        query = f"SELECT * FROM {table_name}"
        df = pd.read_sql_query(query, conn)
        dfs[table_name] = df
        print(f"--- {table_name} DataFrame head ---")
        display(df.head())
        print("\n")

print("All tables loaded into 'dfs' dictionary.")

--- Album DataFrame head ---

   AlbumId                                  Title  ArtistId
0        1  For Those About To Rock We Salute You         1
1        2                      Balls to the Wall         2
2        3                      Restless and Wild         2
3        4                      Let There Be Rock         1
4        5                               Big Ones         3

--- Artist DataFrame head ---

   ArtistId               Name
0         1              AC/DC
1         2             Accept
2         3          Aerosmith
3         4  Alanis Morissette
4         5    Alice In Chains

--- Customer DataFrame head ---

,CustomerId,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
0,1,Luís,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,+55 (12) 3923-5566,luisg@embraer.com.br,3
1,2,Leonie,Köhler,None,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,+49 0711 2842222,None,leonekohler@surfeu.de,5
2,3,François,Tremblay,None,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,+1 (514) 721-4711,None,ftremblay@gmail.com,3
3,4,Bjørn,Hansen,None,Ullevålsveien 14,Oslo,None,Norway,0171,+47 22 44 22 22,None,bjorn.hansen@yahoo.no,4
4,5,František,Wichterlová,JetBrains s.r.o.,Klanova 9/506,Prague,None,Czech Republic,14700,+420 2 4172 5555,+420 2 4172 5555,frantisekw@jetbrains.com,4

--- Employee DataFrame head ---

,EmployeeId,LastName,FirstName,Title,ReportsTo,BirthDate,HireDate,Address,City,State,Country,PostalCode,Phone,Fax,Email
0,1,Adams,Andrew,General Manager,NaN,1962-02-18 00:00:00,2002-08-14 00:00:00,11120 Jasper Ave NW,Edmonton,AB,Canada,T5K 2N1,+1 (780) 428-9482,+1 (780) 428-3457,andrew@chinookcorp.com
1,2,Edwards,Nancy,Sales Manager,1.0,1958-12-08 00:00:00,2002-05-01 00:00:00,825 8 Ave SW,Calgary,AB,Canada,T2P 2T3,+1 (403) 262-3443,+1 (403) 262-3322,nancy@chinookcorp.com
2,3,Peacock,Jane,Sales Support Agent,2.0,1973-08-29 00:00:00,2002-04-01 00:00:00,1111 6 Ave SW,Calgary,AB,Canada,T2P 5M5,+1 (403) 262-3443,+1 (403) 262-6712,jane@chinookcorp.com
3,4,Park,Margaret,Sales Support Agent,2.0,1947-09-19 00:00:00,2003-05-03 00:00:00,683 10 Street SW,Calgary,AB,Canada,T2P 5G3,+1 (403) 263-4423,+1 (403) 263-4289,margaret@chinookcorp.com
4,5,Johnson,Steve,Sales Support Agent,2.0,1965-03-03 00:00:00,2003-10-17 00:00:00,7727B 41 Ave,Calgary,AB,Canada,T3B 1Y7,1 (780) 836-9987,1 (780) 836-9543,steve@chinookcorp.com

--- Genre DataFrame head ---

   GenreId                Name
0        1                Rock
1        2                Jazz
2        3               Metal
3        4  Alternative & Punk
4        5       Rock And Roll

--- Invoice DataFrame head ---

,InvoiceId,CustomerId,InvoiceDate,BillingAddress,BillingCity,BillingState,BillingCountry,BillingPostalCode,Total
0,1,2,2021-01-01 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,1.98
1,2,4,2021-01-02 00:00:00,Ullevålsveien 14,Oslo,None,Norway,0171,3.96
2,3,8,2021-01-03 00:00:00,Grétrystraat 63,Brussels,None,Belgium,1000,5.94
3,4,14,2021-01-06 00:00:00,8210 111 ST NW,Edmonton,AB,Canada,T6G 2C7,8.91
4,5,23,2021-01-11 00:00:00,69 Salem Street,Boston,MA,USA,2113,13.86

--- InvoiceLine DataFrame head ---

   InvoiceLineId  InvoiceId  TrackId  UnitPrice  Quantity
0              1          1        2       0.99         1
1              2          1        4       0.99         1
2              3          2        6       0.99         1
3              4          2        8       0.99         1
4              5          2       10       0.99         1

--- MediaType DataFrame head ---

   MediaTypeId                         Name
0            1              MPEG audio file
1            2     Protected AAC audio file
2            3  Protected MPEG-4 video file
3            4     Purchased AAC audio file
4            5               AAC audio file

--- Playlist DataFrame head ---

   PlaylistId        Name
0           1       Music
1           2      Movies
2           3    TV Shows
3           4  Audiobooks
4           5  90’s Music

--- PlaylistTrack DataFrame head ---

   PlaylistId  TrackId
0           1     3402
1           1     3389
2           1     3390
3           1     3391
4           1     3392

--- Track DataFrame head ---

,TrackId,Name,AlbumId,MediaTypeId,GenreId,Composer,Milliseconds,Bytes,UnitPrice
0,1,For Those About To Rock (We Salute You),1,1,1,"Angus Young, Malcolm Young, Brian Johnson",343719,11170334,0.99
1,2,Balls to the Wall,2,2,1,"U. Dirkschneider, W. Hoffmann, H. Frank, P. Ba...",342562,5510424,0.99
2,3,Fast As a Shark,3,2,1,"F. Baltes, S. Kaufman, U. Dirkscneider & W. Ho...",230619,3990994,0.99
3,4,Restless and Wild,3,2,1,"F. Baltes, R.A. Smith-Diesel, S. Kaufman, U. D...",252051,4331779,0.99
4,5,Princess of the Dawn,3,2,1,Deaffy & R.A. Smith-Diesel,375418,6290521,0.99

All tables loaded into 'dfs' dictionary.

In [32]:
import pandas as pd
import sqlite3

# 데이터베이스 연결
conn = sqlite3.connect(DB_PATH)

# Read data from a table into a pandas DataFrame
# Replace 'albums' with one of the available table names listed above.
query = "SELECT * FROM Album"
df = pd.read_sql_query(query, conn)

# Close the connection
conn.close()

# Display the first few rows of the DataFrame
df

     AlbumId                                              Title  ArtistId
0          1              For Those About To Rock We Salute You         1
1          2                                  Balls to the Wall         2
2          3                                  Restless and Wild         2
3          4                                  Let There Be Rock         1
4          5                                           Big Ones         3
..       ...                                                ...       ...
342      343                             Respighi:Pines of Rome       226
343      344  Schubert: The Late String Quartets & String Qu...       272
344      345                                Monteverdi: L'Orfeo       273
345      346                              Mozart: Chamber Music       274
346      347  Koyaanisqatsi (Soundtrack from the Motion Pict...       275

[347 rows x 3 columns]

In [33]:
def summarize_df(df: pd.DataFrame) -> pd.DataFrame:
    # 데이터프레임의 각 컬럼별 데이터 타입, 결측치 수/비율, 대표값 5개를 요약한 DataFrame을 반환합니다.
    summary_data = []
    for col in df.columns:
        dtype = df[col].dtype
        n_unique = df[col].nunique()
        null_cnt = df[col].isnull().sum()
        null_ratio = round((null_cnt / len(df)) * 100, 2)
        unique_vals = df[col].dropna().unique()
        sample_vals = list(unique_vals[:7])

        summary_data.append({
            'Column': col,
            'N_Unique': n_unique,
            'Dtype': dtype,
            'Null_Count': null_cnt,
            'Null_Ratio(%)': null_ratio,
            'Sample_Values_5': sample_vals
        })

    return pd.DataFrame(summary_data)

In [34]:
output_excel_path = 'all_tables_summary.xlsx'

# openpyxl 엔진을 사용하여 Excel 파일을 생성합니다. (Colab 기본 탑재)
with pd.ExcelWriter(output_excel_path, engine='openpyxl') as writer:
    for table_name, df in dfs.items():
        print(f"Summarizing {table_name}...")
        summary_df = summarize_df(df)
        # Write each summary DataFrame to a separate sheet
        summary_df.to_excel(writer, sheet_name=table_name, index=False)
        print(f"Summary for {table_name} written to sheet '{table_name}'.")

print(f"All table summaries saved to '{output_excel_path}'")

Summarizing Album...
Summary for Album written to sheet 'Album'.
Summarizing Artist...
Summary for Artist written to sheet 'Artist'.
Summarizing Customer...
Summary for Customer written to sheet 'Customer'.
Summarizing Employee...
Summary for Employee written to sheet 'Employee'.
Summarizing Genre...
Summary for Genre written to sheet 'Genre'.
Summarizing Invoice...
Summary for Invoice written to sheet 'Invoice'.
Summarizing InvoiceLine...
Summary for InvoiceLine written to sheet 'InvoiceLine'.
Summarizing MediaType...
Summary for MediaType written to sheet 'MediaType'.
Summarizing Playlist...
Summary for Playlist written to sheet 'Playlist'.
Summarizing PlaylistTrack...
Summary for PlaylistTrack written to sheet 'PlaylistTrack'.
Summarizing Track...
Summary for Track written to sheet 'Track'.
All table summaries saved to 'all_tables_summary.xlsx'

In [35]:
from google.colab import files

# Download the generated Excel file
files.download('all_tables_summary.xlsx')

In [36]:
from google.colab import userdata
SUPABASE_KEY = userdata.get('superman')
print(SUPABASE_KEY[::2])

rdns2

In [38]:
# @title supabase
from google.colab import userdata

try:
    # 왼쪽 열쇠 아이콘(🔑 보안 비밀)에 'supakey'를 이름으로 지정하고 실제 API Key를 값으로 추가해 주세요.
    SUPABASE_KEY = userdata.get('supakey')
    print("✅ 보안 비밀 'supakey' 로드 성공!")
except Exception as e:
    SUPABASE_KEY = None
    print("❌ 오류: 코랩 보안 비밀 설정이 필요합니다.")
    print("👉 해결 방법: 왼쪽 메뉴의 🔑(열쇠 아이콘)에서 이름은 'supakey'로 생성하시고, 실제 Key 값을 입력한 다음 '노트북 액세스' 권한을 활성화해 주세요.\n")
    print(f"상세 오류 메시지: {e}\n")

# 접속이 되는 지 사전 확인
import socket
from urllib.parse import urlparse

SUPABASE_URL = "https://qctwuimxnppnzmjcnluc.supabase.co"
hostname = urlparse(SUPABASE_URL).hostname

try:
    ip = socket.gethostbyname(hostname)
    print(f"DNS 조회 성공 (IP: {ip})")
except socket.gaierror as e:
    print(f"DNS 조회 실패: {e}")

❌ 오류: 코랩 보안 비밀 설정이 필요합니다.
👉 해결 방법: 왼쪽 메뉴의 🔑(열쇠 아이콘)에서 이름은 'supakey'로 생성하시고, 실제 Key 값을 입력한 다음 '노트북 액세스' 권한을 활성화해 주세요.

상세 오류 메시지: Secret supakey does not exist.

DNS 조회 성공 (IP: 172.64.149.246)

In [39]:
# 0. PostgreSQL 연결에 필요한 드라이버 패키지 설치
!pip install -q psycopg2-binary

import sqlite3
import pandas as pd
from sqlalchemy import create_engine

# 1. Supabase PostgreSQL 연결 정보 설정
# ⚠️ 아래 정보를 본인의 실제 Supabase Database 정보로 변경하셔야 정상 작동합니다.
DB_USER = "postgres"
DB_PASSWORD = "your_supabase_password"  # 👈 여기에 실제 DB 비밀번호를 입력하세요.
DB_HOST = "db.xxxx.supabase.co"       # 👈 여기에 실제 Supabase 호스트 주소를 입력하세요.
DB_PORT = "5432"
DB_NAME = "postgres"

# SQLAlchemy 엔진 생성 (psycopg2 드라이버 명시)
DATABASE_URL = f"postgresql+psycopg2://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}"
engine = create_engine(DATABASE_URL)

# 2. with 구문으로 로컬 SQLite chinook.db 읽기
try:
    with sqlite3.connect('chinook.db') as sqlite_conn:
        # 모든 테이블 목록 조회
        table_names = pd.read_sql(
            "SELECT name FROM sqlite_master WHERE type='table';",
            sqlite_conn
        )['name'].tolist()

        # 3. 각 테이블을 읽어서 Supabase(PostgreSQL)로 전송
        for table in table_names:
            print(f"'{table}' 테이블 업로드 중...")

            # 로컬에서 데이터프레임으로 읽기
            df = pd.read_sql(f"SELECT * FROM {table}", sqlite_conn)

            # PostgreSQL 표준에 맞게 테이블 이름을 소문자로 변환
            target_table = table.lower()

            # Supabase로 데이터프레임 적재 (to_sql 활용)
            df.to_sql(
                name=target_table,
                con=engine,
                if_exists='replace',
                index=False
            )

    print("🎉 모든 Chinook 테이블이 Supabase로 성공적으로 마이그레이션되었습니다!")

except Exception as e:
    print("\n❌ 오류가 발생했습니다. DB_HOST와 DB_PASSWORD가 실제 값으로 정확히 변경되었는지 확인해 주세요.")
    print(f"상세 오류: {e}")

'Album' 테이블 업로드 중...

❌ 오류가 발생했습니다. DB_HOST와 DB_PASSWORD가 실제 값으로 정확히 변경되었는지 확인해 주세요.
상세 오류: (psycopg2.OperationalError) could not translate host name "db.xxxx.supabase.co" to address: Name or service not known

(Background on this error at: https://sqlalche.me/e/21/e3q8)

In [41]:
import sqlite3
import pandas as pd

# SQLite 데이터베이스 연결
DB_PATH = 'chinook.db'

with sqlite3.connect(DB_PATH) as conn:
    # 고객별 총 구매 항목 수(Quantity) 및 총 구매 금액(Total) 집계 쿼리
    query = """
    SELECT
        c.CustomerId,
        c.FirstName || ' ' || c.LastName AS CustomerName,
        c.Country,
        SUM(il.Quantity) AS TotalTracksPurchased,
        ROUND(SUM(il.UnitPrice * il.Quantity), 2) AS TotalSpent
    FROM Customer c
    JOIN Invoice i ON c.CustomerId = i.CustomerId
    JOIN InvoiceLine il ON i.InvoiceId = il.InvoiceId
    GROUP BY c.CustomerId
    ORDER BY TotalTracksPurchased DESC, TotalSpent DESC
    LIMIT 5;
    """

    top_customers_df = pd.read_sql_query(query, conn)

display(top_customers_df)

,CustomerId,CustomerName,Country,TotalTracksPurchased,TotalSpent
0,6,Helena Holý,Czech Republic,38,49.62
1,26,Richard Cunningham,USA,38,47.62
2,57,Luis Rojas,Chile,38,46.62
3,45,Ladislav Kovács,Hungary,38,45.62
4,46,Hugh O'Reilly,Ireland,38,45.62